---
functional:
  - Возможность смены языка сайта
  - Возможность зарегистрироваться на сайте
  - Возможность провести онлайн-матч с другим пользователем сайта
  - Возможность провести онлайн-матч с другом путем отправки ему ссылки на игру
  - Возможность провести матч с ботом
  - Возможность провести пробный матч без регистрации
  - Возможность выбрать уровень сложности матча
  - Наличие способа регулировать максимальное время матча
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implict:
  - Интерфейс сайта должен быть интуитивно понятным(например, когда открывается окно с сообщением о победе в матче, кнопка закрытия окна должна находитьсяв правом верхнем углу)
  - Окно чата с соперником должно занимать достаточно места, чтобы пользователь видел последние несколько сообщений и располагаться так, чтобы не мешать написанию кода, при этом окно должно органично смотреться в системе с другими элементами страницы матча
  - Шрифт текста должен быть не слишком мелким и читаемым
  - Весь код должен прогоняться через линтеры  
